version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    networks:
      - traefik
  kafka:
    image: wurstmeister/kafka:1.1.0
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "customer:5:1"
    networks:
      - traefik
  traefik:
    image: traefik:demo
    build: traefik
   # command: -c /dev/null --web --docker --docker.usebindportip --docker.swarmmode --logLevel=DEBUG
    #command: -c /dev/null --web --docker --docker.swarmmode --logLevel=DEBUG
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
      - traefik
  mysql:
    build: mysql
    image: mysql:demo
    environment:
     MYSQL_ROOT_PASSWORD: "password"
     MYSQL_USER: "dbuser"
     MYSQL_PASSWORD: "dbpass"
    networks:
      - traefik
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
	# docker pull phpmyadmin/phpmyadmin:latest 
    environment:
     PMA_ARBITRARY: 1
     PMA_HOST: mysql
     MYSQL_USER: dbuser
     MYSQL_PASSWORD: dbpass
     MYSQL_ROOT_PASSWORD: password
     PMA_USER: admin
     PMA_PASSWORD: admin
    ports:
      - "8282:80"
    networks:
      - traefik
  customer:
    build: ../microservice-demo-create-customer
    image: customer:demo 
    restart: on-failure
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
     - mysql
    deploy:
      replicas: 1
      labels:
       - "traefik.port=8080"
       - "traefik.backend=customer"
       - "traefik.frontend.rule=Host:docker;PathPrefixStrip:/micro-customer/"
       - "traefik.frontend.entryPoints=http"
       - "traefik.tags=web"
       - "traefik.backend.healthcheck.path=/health"
       - "traefik.backend.healthcheck.port=8080"
       - "traefik.backend.healthcheck.interval=5s"
    networks:
      - traefik
  rdv:
    build: ../microservice-demo-create-rdv
    image: rdv:demo
    restart: on-failure
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    deploy:
      labels:
       - "traefik.port=8080"
       - "traefik.backend=rdv"
       - "traefik.frontend.rule=Host:docker;PathPrefixStrip:/micro-rdv/"
       - "traefik.frontend.entryPoints=http"
       - "traefik.tags=web"
    networks:
      - traefik
    depends_on:
     - mysql
  viz:
    image: dockersamples/visualizer:latest
	# docker pull dockersamples/visualizer:latest
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
     - "8181:8080"
    networks:
     - webgateway
networks:
  webgateway:
    driver: overlay
   # external: true
  traefik:
    driver: overlay
